yujia/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yujiaxm.urls')),

]

yujiaxm/urls.py
from django.urls import path
from .views import *

app_name='yujiaxm'

urlpatterns = [
    path('',login,name='login'),
    path('register/',register,name='register'),
    path("index", index), # 我的
    path('history/',history),
    path('search/',search),
    path('discovery/',discovery,name='discovery'),
    path('exploration_<con>/',exploration),
    
    path('yyxq_<d_id>/', yyxq,name="yyxq"),
    path('ddxq_<id>/', ddxq,name="ddxq"),
    path('fabu/', fabu,name="fabu"),  # 发布
    path('duihua1/', duihua1, name="duihua1"),  # 聊天
    path('duihua2/', duihua2, name="duihua2"),  # 聊天
    path('changguanxq_<id>/',changguanxq,name="changguanxq"),
    path('dongzuoxq/',dj_swan,name="dongzuoxq"),
    path('xk_<c_id>/',xk,name="xk"),
    path('ddxqb/',ddxqb,name='ddxqb'),

    path('order/',order,name='order'),
    path('act/',act,name='act'),
    path('category/',category,name='category'),
    path('find/',find,name='find'),
    path('music/',music,name='music'),
    path('songs<id>/',songs,name='songs'),
    path('position/', position, name='position'),

    path('bank_<id>/', bank, name='bank'),
    path('period_<id>/', period, name='period'),
]

yujiaxm/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class info(models.Model):
    u=models.OneToOneField(to=User,on_delete=models.CASCADE)
    password = models.CharField(max_length=6, verbose_name='密码')
    distance=models.CharField(max_length=200)
    name=models.CharField(max_length=20,default='')

class Search(models.Model):
   time=models.DateTimeField(auto_now_add=True)
   times=models.IntegerField(default=0)
   con=models.CharField(max_length=100)

class Place(models.Model):
   class Meta:
      verbose_name = "场馆"
      verbose_name_plural = "场馆"

   name = models.CharField(max_length=30, verbose_name="所属区域")
   username = models.CharField(max_length=30, verbose_name="场馆名称", default="")
   img = models.ImageField(upload_to="img/", default="", verbose_name="场馆图片")
   place = models.CharField(max_length=50, verbose_name="地点", default="")
   distance = models.CharField(max_length=30, verbose_name="距离", default="")
   assess = models.IntegerField(default=1, choices=(
      (1, "一星"),
      (2, "二星"),
      (3, "三星"),
      (4, "四星"),
      (5, "五星"),
   ))


class Venue_details(models.Model):
    c_id = models.ForeignKey(to=Place, verbose_name="场馆id", on_delete=models.CASCADE)
    server = models.CharField(verbose_name="服务", max_length=20, default='')
    tese = models.CharField(verbose_name="场馆特色", max_length=20, default='')
    phnumber = models.CharField(max_length=200, verbose_name="联系电话", default="")
    class Meta:
        verbose_name_plural="场馆详情"

class Pinglun(models.Model):
    con = models.TextField(max_length=200,verbose_name="评论内容")
    author = models.ForeignKey(to=User,verbose_name="作者",on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)
    c_id = models.ForeignKey(to=Place,verbose_name="评价场馆",on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural="评论"

class Xuanke(models.Model):
    riqi = models.DateField(verbose_name='有限日期', auto_now_add=False)
    shijianduan = models.CharField(verbose_name='时间段', max_length=100)
    didian = models.CharField(max_length=100, verbose_name='房间')
    neirong = models.CharField(max_length=100,verbose_name='授课内容')
    chance = models.CharField(max_length=10,verbose_name='场次',default="")
    price = models.CharField(max_length=100,verbose_name='金额')
    renshu = models.IntegerField(verbose_name="人数")
    c_id=models.ForeignKey(to=Place,on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural="选课"

class Dingdan(models.Model):
    name = models.ForeignKey(to=Place,max_length=30,verbose_name="场馆名称",on_delete=models.CASCADE)
    xuke_id = models.ForeignKey(to=Xuanke,verbose_name="选课id",on_delete=models.CASCADE)
    author = models.ForeignKey(to=User,verbose_name="创建人",on_delete=models.CASCADE)
    price = models.CharField(max_length=100,verbose_name="金额")
    type = models.IntegerField(verbose_name="支付状态",default=0)
    riqi = models.DateField(verbose_name="日期",auto_now_add=False)
    shijianduan = models.CharField(verbose_name="时间段",max_length=100,default='')
    chance = models.CharField(max_length=10, verbose_name='场次', default="")
    c_time=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    class Meta:
        verbose_name_plural="订单详情"

class Dongzuo(models.Model):
    name = models.CharField(verbose_name='动作名称',max_length=100)
    img = models.ImageField(verbose_name='动作图片',default="")
    class Meta:
        verbose_name_plural="动作"

class Dongzuo_details(models.Model):
    name = models.ForeignKey(to=Dongzuo,max_length=40,verbose_name="动作名称",on_delete=models.CASCADE)
    ke_time = models.CharField(max_length=40,verbose_name="课时")
    shi_time = models.CharField(max_length=40,verbose_name="时长")
    rank = models.CharField(max_length=40,verbose_name="难度等级")
    produce = models.CharField(max_length=400,verbose_name="介绍")
    people = models.CharField(max_length=400,verbose_name="人群")
    video_name = models.CharField(max_length=40,verbose_name="视频名称")
    class Meta:
        verbose_name_plural="动作详情"
class Category(models.Model):
    class Meta:
        verbose_name = "课程分类"
        verbose_name_plural = "课程分类"
    name = models.CharField(max_length=30,verbose_name="分类名称")
    title = models.CharField(max_length=30,verbose_name="标题")
    people = models.IntegerField(verbose_name="参加人数")
    img = models.ImageField(upload_to="img/",default="",verbose_name="分类图片")
class Music(models.Model):
    class Meta:
        verbose_name = "瑜伽音乐"
        verbose_name_plural = "瑜伽音乐"
    name = models.CharField(max_length=30,verbose_name="歌单分类名称")
    img = models.ImageField(upload_to="img/",default="",verbose_name="歌单分类背景图片")

class Act(models.Model):
    class Meta:
        verbose_name = "动作库"
        verbose_name_plural = "动作库"
    name = models.CharField(max_length=30,verbose_name="动作分类名称")
    img = models.ImageField(upload_to="img/",default="",verbose_name="动作分类背景图片")
class Song(models.Model):
    class Meta:
        verbose_name = "歌名"
        verbose_name_plural = "歌名"
    name = models.CharField(max_length=30,verbose_name="歌名")
    t = models.ForeignKey(to=Music,to_field='id',verbose_name="所属分类",on_delete=models.CASCADE)


class BankCard(models.Model):
    y = models.ForeignKey(to=User, on_delete=models.CASCADE)
    card = models.CharField(max_length=20, verbose_name='银行卡号')
    people = models.CharField(max_length=20, verbose_name='持有人')
    vest = models.CharField(max_length=100, verbose_name='银行卡归属')
    Type = models.CharField(max_length=100, verbose_name='类型')
    phone = models.CharField(max_length=11, verbose_name='手机号')
    balance = models.IntegerField(verbose_name='余额')

yujiaxm/forms.py
from django.forms import ModelForm,Form,CharField,PasswordInput,TextInput
from django.contrib.auth import models,authenticate
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

class Login(Form):
    name = CharField(label='账户名',widget=TextInput(attrs={'placeholder':"请输入您的账号或邮箱"}))
    password = CharField(widget=PasswordInput(attrs={'placeholder':"请输入密码"}),label='密码')
    class Meta:
        model = models.User
        fields = ['name','password']
        widgets = {
            'password': PasswordInput
        }
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name',None)
        password = cleaned_data.get('password',None)
        if name and password:
            user=authenticate(username=name,password=password)
            if not user:
                raise ValidationError('用户名密码错误')
            else:
                self.user=user

class Register(Form):
    name = CharField(label='账户名',widget=TextInput(attrs={'placeholder':"请输入您的账号或邮箱"}),error_messages={'required':u'账号重复'})
    password = CharField(widget=PasswordInput(attrs={'placeholder':"请输入验证码"}),label='验证码')
    class Meta:
        model = models.User
        fields = ['name','password']
        widgets = {
            'password': PasswordInput
        }
        labels = {
            'name': '用户名',
            'password': '验证码',
        }
    def clean(self):
        print('------------------')
        cleaned_data = super().clean()
        username = cleaned_data.get("name",None)
        username_list=models.User.objects.all().values_list('username')
        if username:
            for i in username_list:
                if username in i:
                    raise ValidationError(
                        '用户名已存在，请重新输入'
                    )
        return cleaned_data

yujiaxm/views.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from .forms import Login,Register
from django.contrib.auth import login as login1,models
from django.contrib.auth import authenticate,login as login1
from .models import *
from math import radians, cos, sin, asin, sqrt
from django.views.decorators.csrf import csrf_exempt
import json,re
# from geopy.distance import geodesic
# Create your views here.

def login(request):
    if request.method == "GET":
        form = Login()
        return render(request,'zzy/login.html/',{'form':form})
    else:
        form = Login(request.POST)

        if form.is_valid():
            # 成功
            login1(request, form.user)
            jd = request.POST['jd']
            wd = request.POST['wd']
            wz = request.POST['wz']
            if jd and wd and wz:
                if request.user.info:
                    print(123)
                    request.user.info.create(distance='%s,%s' % (jd, wd), name=wz)
                else:
                    request.user.update(distance='%s,%s' % (jd, wd), name=wz)
            return redirect(reverse('yujiaxm:order'))
        else:
            # 验证失败
            return render(request,'zzy/login.html',{'form':form})

def register(request):
    if request.method == 'GET':
        form = Register()
        form.fields['name'].help_text = None
        return render(request, 'zzy/register.html', {'form': form})
    else:
        form = Register(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            from django.contrib.auth.hashers import make_password
            models.User.objects.create(username=data['name'], password=make_password(data['password']))
            return redirect(reverse('yujiaxm:login'))
        else:
            return render(request, 'zzy/register.html', {'form': form})


def index(request):  # 个人中心
    return render(request, "hq/index.html")

def history(request):  # 历史搜索
    return render(request,"hq/history.html")

def search(request): # 搜索界面
    obj=Search.objects.all().order_by('-times')
    if len(obj)>4:
        obj=obj[0:4]
    return render(request,"hq/search.html",{'obj':obj})

def exploration(request,con): #　结果
    if request.method == 'GET':
        obj=Search.objects.filter(con=con)
        if obj:
            Search.objects.filter(con=con).update(times=Search.objects.filter(con=con)[0].times+1)
        else:
            Search.objects.create(con=con)
    obj=Place.objects.all()
    res=[]
    yjd,ywd=request.user.info.distance.split(',')
    jl_list=[]
    for i in obj:
        if con in i.username:
            xjd,xwd=i.distance.split(',')
            jl=round(haversine(float(yjd), float(ywd), float(xjd), float(xwd)),2)
            jl_list.append(jl)
            print(i)
            res.append(i)
    if len(res)==0:
        return redirect(reverse('yujiaxm:discovery'))
    lbt=[]
    if len(res)>3:
        lbt=res[0:3]
    return render(request,"hq/exploration.html",{'res':res,'num':len(res),'str':str,'lbt':lbt,'jl_list':jl_list})

# 计算距离
def haversine(lon1, lat1, lon2, lat2):  # 经度1，纬度1，经度2，纬度2 （十进制度数）
    # 将十进制度数转化为弧度
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine公式
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * asin(sqrt(a))
    r = 6371  # 地球平均半径，单位为公里
    return c * r

def discovery(request): # 无
    return render(request,"hq/Discovery.html")



def yyxq(request,d_id):
    if d_id:
        dd = Dingdan.objects.filter(id=d_id)[0]
        return render(request,'xing/xing-yyxq.html',{'i':dd})

def ddxq(request,id):
    xk = Xuanke.objects.filter(id=id)[0]
    dd=[]
    if id:
        Dingdan.objects.create(author=request.user,name=xk.c_id,xuke_id=xk,price=xk.price,riqi=xk.riqi,shijianduan=xk.shijianduan,chance=xk.chance)
        dd=Dingdan.objects.all().order_by('-c_time').first()
    print(dd)
    return render(request,'xing/xing-ddxq.html',{'dd':dd})

@csrf_exempt
def xk(request,c_id):

    xk = Xuanke.objects.filter(c_id=c_id)
    return render(request,'xing/scheduled.html',{'xk':xk})


def fabu(request):
    return render(request,'xing/xing-fabu.html')

def duihua1(request):
    return render(request,'xing/xing-duihua1.html')

def duihua2(request):
    return render(request,'xing/xing-duihua2.html')

def changguanxq(request,id):
    vd=[]
    pl=[]
    try:
        vd = Venue_details.objects.filter(c_id=Place.objects.filter(id=id)[0])[0]
        pl = Pinglun.objects.filter(c_id=Place.objects.filter(id=id)[0])
    except:
        pass
    print(pl)
    return render(request,'xing/dj_index.html',{'vd':vd,'pl':pl,'id':id})

def dj_swan(request):
    dd = Dongzuo_details.objects.all
    return render(request,'xing/dj_swan.html',{'dd':dd})


def ddxqb(request):
    if request.user:
        dd = Dingdan.objects.filter(author=request.user)
        return render(request,'xing/xing-ddxqb.html',{'dd':dd})
    else:
        return redirect(reverse('yujiaxm:login'))


@csrf_exempt
def order(request):
    list_order = list(Place.objects.all().values())
    place = request.POST.get('place')

    print(place)
    # lnglat = str(request.POST.get('lnglat'))
    # print(lnglat)
    # s = tuple(re.findall("\d+.\d+", lnglat))
    # print(s)
    # distance = list(Place.objects.all().values('distance'))
    # print(distance)
    # for item in distance:
    #     item_dis = item['distance']
    #     print(item_dis)
        # data4 = geodesic((s), (item_dis))
        # print(data4)
    # data4=geodesic((37.82851,112.55176),(37.82861,112.55256))
    # print(data4)
    try:
        data = request.POST.get('data')
        data1 = json.loads(data)['city']
        data2 = json.loads(data)['district']
        data3 = []
        data3.append(data1)
        data3.append(data2)

        message={
            # 'm':list_order,
            's':data3,
            # 'm':data4,
        }
        return HttpResponse(json.dumps(message,ensure_ascii=False))
    except:
        return render(request, 'yoga/order.html', {'list_order': list_order,'place':place})

def act(request):
    act = Act.objects.all().values()
    return render(request,'yoga/act.html',{'act':act})
def category(request):
    cate = Category.objects.all().values()
    return render(request,'yoga/category.html',{'cate':cate})
def music(request):
    music = Music.objects.all().values()
    return render(request,'yoga/music.html',{'music':music})
def find(request):
    list_order = list(Place.objects.all().values())
    print(list_order)
    assess = list(Place.objects.all().values('assess'))
    print(assess)
    for i, v in enumerate(list_order):
        v['assess'] = assess[i]['assess']
    print(list_order)
    return render(request,'yoga/find.html',{'list_order':list_order})
def songs(request,id):
    songs = Music.objects.filter(id=id).values()
    gq = Song.objects.filter(t_id=id).values()
    print(gq)
    return render(request,'yoga/songs.html',{'songs':songs,'gq':gq})
def position(request):
    return render(request, 'yoga/position.html')


# 郑博

# 选择付款方式
@csrf_exempt
def period(request,id):
    dd = Dingdan.objects.filter(id=id).first()
    price = Dingdan.objects.filter(id=id).first()
    return render(request, 'zb/Payments.html', {'price':price, 'dd':dd})

# 银行卡付款
@csrf_exempt
def bank(request,id):
    user_id = request.user.id
    yh = BankCard.objects.filter(y_id=user_id).all()
    price = Dingdan.objects.filter(id=id).first()
    dd = Dingdan.objects.filter(id=id).first()
    if request.method == "POST":
        fl=request.POST.get('pas',None)
        if fl:
            password = request.user.info.password
            if password == fl:
                user = request.user.username
                ye = request.POST.get('yue', None)
                xf = request.POST.get('xf', None)
                kh = request.POST.get('kahao', None)
                kou = int(ye)-int(xf)
                BankCard.objects.filter(card=kh).update(balance=kou)
                return HttpResponse('ok')
            else:
                return HttpResponse('密码错误')
        else:
            return HttpResponse('网络连接中断')
    else:
        return render(request, 'zb/payment.html',{'yh':yh ,'price':price, 'dd':dd})

yujiaxm/templates/zb/Payments.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'zb/css/Payments.css'%}">
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_995597_mk2ggpu1c2k.css">
    <script type="text/javascript" src="https://at.alicdn.com/t/font_995597_zgkloknmu8.js"></script>
    <link rel="stylesheet" href="{% static 'zb/css/swiper.css'%}">
    <script src="{% static 'zb/js/rem.js'%}"></script>
    <script src="{% static 'zb/js/jQuery.js'%}"></script>
    <script src="{% static 'zb/js/swiper.js'%}"></script>
    <title>付款方式</title>
</head>
<body>
<header>
    <i class="iconfont icon-zuojiantou"></i>
</header>
<div class="way">付款方式</div>
<div class="figure">
    <div class="figure-L">
        <div></div>
        <span>您本次消费的金额</span>
    </div>
    <div class="figure-R">
        <h5>RMB</h5>
        <span>{{ price.price }}</span>
    </div>
</div>
<main>
    <ul>
        <li>
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-zhifubao"></use>
            </svg>
            <h4>支付宝支付</h4>
            <h5>ALIPAY</h5>
        </li>
        <li>
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-weixin"></use>
            </svg>
            <h4>微信支付</h4>
            <h5>WACHAT PAY</h5>
        </li>
        <a href="{% url 'yujiaxm:bank' id=dd.id%}">
        <li>
            <svg class="icon" aria-hidden="true">
                <use xlink:href="#icon-yinhangqia"></use>
            </svg>
            <h4>银行卡支付</h4>
            <h5>BANKCARD PAY</h5>
        </li>
        </a>
        <li>
            <h4>EMPTY</h4>
        </li>
    </ul>
</main>
</body>
</html>
<style type="text/css">
    .icon {
       width: .66em; height: .66em;
       vertical-align: -0.15em;
       fill: currentColor;
       overflow: hidden;
       margin-bottom: .22rem
    }
</style>

yujiaxm/templates/zb/scheduled.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'zb/css/scheduled.css'%}">
    <link rel="stylesheet" href="https://at.alicdn.com/t/font_995597_91v4xjof2mr.css">
    <script src='https://at.alicdn.com/t/font_995597_e9rzzbvg1on.js'></script>
    <link rel="stylesheet" href="{% static 'zb/css/swiper.css'%}">
    <script src="{% static 'zb/js/rem.js'%}"></script>
    <script src="{% static 'zb/js/jQuery.js'%}"></script>
    <script src="{% static 'zb/js/swiper.js'%}"></script>
    <title>课时预定</title>
</head>
<body>
<header>
    <i class="iconfont icon-zuojiantou"></i>
</header>
<div class="way">课时预定</div>
<main>
    <ul>
        {% for item in xk %}
        <li>
            <span class='cl'>{{ item.id }}</span>
            <div class='RMB'>
                <p>RMB</p>
                <span class='RMB1'>{{ item.price }}</span>
            </div>
            <div class='tanchu' style='display: none'>
                这是弹出界面
            </div>
        </li>
        {% endfor %}
    </ul>
</main>
<div class='tk'>
    <input type="checkbox">
    <span>我已阅读并同意服务条款</span>
</div>
<div class='amount'>
    <svg class="icon" aria-hidden="true">
            <use xlink:href="#icon-yinhangqia1"></use>
    </svg>
    <p>请确定您本次消费的金额</p>
    <div class='amount-money'>
        <p>RMB</p>
        <span></span>
    </div>
    
    <a class='amount-y'>确定并支付</a>
   
</div>
</body>
<script>
    $('main ul li').click(function(){
        $('main ul li').css("background","#fdfdfd");
        $('main ul li').children().css('color','#a1a1a1')
        $('main ul li').children().children().css('color','#a1a1a1')
        $('main ul li').css('margin-bottom','.26rem')
        $('.tanchu').css('display','none')
        $(this).css("background","#fff");
        $(this).children().css('color','#79d7f2')
        $(this).children().children().css('color','#79d7f2')
        if($(this).children().css('color')=='rgb(121, 215, 242)'){
            $(this).find('.tanchu').slideDown()
            $(this).css('margin-bottom','.9rem')
            a = $(this).find('.RMB1').text()
            $('.amount-money').find('span').text(a)
        }

    })
    if($('.tk input').is(':checked')){

        }
    else{
        $('.amount-y').css('background-image','linear-gradient(to left,#BBB,#BBBBBB)')
        }
    $('.tk input').click(function(){
        if($('.tk input').is(':checked')){
         $('.amount-y').css('background-image','linear-gradient(to left,#76def5,#5cd0e8)')
        }
        else{
        $('.amount-y').css('background-image','linear-gradient(to left,#BBB,#BBBBBB)')
        }
    })
    $('.amount-y').click(function(){
        if($('.tk input').is(':checked')){
            $('.amount-y').attr('href',"{% url 'yujiaxm:period' %}")
        }
        else{
            alert('请阅读条款')
        }
    })

</script>
</html>