yujia/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yujiaxm.urls')),

]

yujiaxm/urls.py
from django.urls import path
from .views import *

app_name='yujiaxm'

urlpatterns = [
    path('',login,name='login'),
    path('register/',register,name='register'),
    path("index", index), # 我的
    path('history/',history),
    path('search/',search),
    path('discovery/',discovery,name='discovery'),
    path('exploration_<con>/',exploration),
    
    path('yyxq_<d_id>/', yyxq,name="yyxq"),
    path('ddxq_<id>/', ddxq,name="ddxq"),
    path('fabu/', fabu,name="fabu"),  # 发布
    path('duihua1/', duihua1, name="duihua1"),  # 聊天
    path('duihua2/', duihua2, name="duihua2"),  # 聊天
    path('changguanxq_<id>/',changguanxq,name="changguanxq"),
    path('dongzuoxq/',dj_swan,name="dongzuoxq"),
    path('xk_<c_id>/',xk,name="xk"),
    path('ddxqb/',ddxqb,name='ddxqb'),

    path('order/',order,name='order'),
    path('act/',act,name='act'),
    path('category/',category,name='category'),
    path('find/',find,name='find'),
    path('music/',music,name='music'),
    path('songs<id>/',songs,name='songs'),
    path('position/', position, name='position'),

    path('bank_<id>/', bank, name='bank'),
    path('period_<id>/', period, name='period'),
]

yujiaxm/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class info(models.Model):
    u=models.OneToOneField(to=User,on_delete=models.CASCADE)
    password = models.CharField(max_length=6, verbose_name='密码')
    distance=models.CharField(max_length=200)
    name=models.CharField(max_length=20,default='')

class Search(models.Model):
   time=models.DateTimeField(auto_now_add=True)
   times=models.IntegerField(default=0)
   con=models.CharField(max_length=100)

class Place(models.Model):
   class Meta:
      verbose_name = "场馆"
      verbose_name_plural = "场馆"

   name = models.CharField(max_length=30, verbose_name="所属区域")
   username = models.CharField(max_length=30, verbose_name="场馆名称", default="")
   img = models.ImageField(upload_to="img/", default="", verbose_name="场馆图片")
   place = models.CharField(max_length=50, verbose_name="地点", default="")
   distance = models.CharField(max_length=30, verbose_name="距离", default="")
   assess = models.IntegerField(default=1, choices=(
      (1, "一星"),
      (2, "二星"),
      (3, "三星"),
      (4, "四星"),
      (5, "五星"),
   ))


class Venue_details(models.Model):
    c_id = models.ForeignKey(to=Place, verbose_name="场馆id", on_delete=models.CASCADE)
    server = models.CharField(verbose_name="服务", max_length=20, default='')
    tese = models.CharField(verbose_name="场馆特色", max_length=20, default='')
    phnumber = models.CharField(max_length=200, verbose_name="联系电话", default="")
    class Meta:
        verbose_name_plural="场馆详情"

class Pinglun(models.Model):
    con = models.TextField(max_length=200,verbose_name="评论内容")
    author = models.ForeignKey(to=User,verbose_name="作者",on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name="创建时间",auto_now_add=True)
    c_id = models.ForeignKey(to=Place,verbose_name="评价场馆",on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural="评论"

class Xuanke(models.Model):
    riqi = models.DateField(verbose_name='有限日期', auto_now_add=False)
    shijianduan = models.CharField(verbose_name='时间段', max_length=100)
    didian = models.CharField(max_length=100, verbose_name='房间')
    neirong = models.CharField(max_length=100,verbose_name='授课内容')
    chance = models.CharField(max_length=10,verbose_name='场次',default="")
    price = models.CharField(max_length=100,verbose_name='金额')
    renshu = models.IntegerField(verbose_name="人数")
    c_id=models.ForeignKey(to=Place,on_delete=models.CASCADE)
    class Meta:
        verbose_name_plural="选课"

class Dingdan(models.Model):
    name = models.ForeignKey(to=Place,max_length=30,verbose_name="场馆名称",on_delete=models.CASCADE)
    xuke_id = models.ForeignKey(to=Xuanke,verbose_name="选课id",on_delete=models.CASCADE)
    author = models.ForeignKey(to=User,verbose_name="创建人",on_delete=models.CASCADE)
    price = models.CharField(max_length=100,verbose_name="金额")
    type = models.IntegerField(verbose_name="支付状态",default=0)
    riqi = models.DateField(verbose_name="日期",auto_now_add=False)
    shijianduan = models.CharField(verbose_name="时间段",max_length=100,default='')
    chance = models.CharField(max_length=10, verbose_name='场次', default="")
    c_time=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    class Meta:
        verbose_name_plural="订单详情"

class Dongzuo(models.Model):
    name = models.CharField(verbose_name='动作名称',max_length=100)
    img = models.ImageField(verbose_name='动作图片',default="")
    class Meta:
        verbose_name_plural="动作"

class Dongzuo_details(models.Model):
    name = models.ForeignKey(to=Dongzuo,max_length=40,verbose_name="动作名称",on_delete=models.CASCADE)
    ke_time = models.CharField(max_length=40,verbose_name="课时")
    shi_time = models.CharField(max_length=40,verbose_name="时长")
    rank = models.CharField(max_length=40,verbose_name="难度等级")
    produce = models.CharField(max_length=400,verbose_name="介绍")
    people = models.CharField(max_length=400,verbose_name="人群")
    video_name = models.CharField(max_length=40,verbose_name="视频名称")
    class Meta:
        verbose_name_plural="动作详情"
class Category(models.Model):
    class Meta:
        verbose_name = "课程分类"
        verbose_name_plural = "课程分类"
    name = models.CharField(max_length=30,verbose_name="分类名称")
    title = models.CharField(max_length=30,verbose_name="标题")
    people = models.IntegerField(verbose_name="参加人数")
    img = models.ImageField(upload_to="img/",default="",verbose_name="分类图片")
class Music(models.Model):
    class Meta:
        verbose_name = "瑜伽音乐"
        verbose_name_plural = "瑜伽音乐"
    name = models.CharField(max_length=30,verbose_name="歌单分类名称")
    img = models.ImageField(upload_to="img/",default="",verbose_name="歌单分类背景图片")

class Act(models.Model):
    class Meta:
        verbose_name = "动作库"
        verbose_name_plural = "动作库"
    name = models.CharField(max_length=30,verbose_name="动作分类名称")
    img = models.ImageField(upload_to="img/",default="",verbose_name="动作分类背景图片")
class Song(models.Model):
    class Meta:
        verbose_name = "歌名"
        verbose_name_plural = "歌名"
    name = models.CharField(max_length=30,verbose_name="歌名")
    t = models.ForeignKey(to=Music,to_field='id',verbose_name="所属分类",on_delete=models.CASCADE)


class BankCard(models.Model):
    y = models.ForeignKey(to=User, on_delete=models.CASCADE)
    card = models.CharField(max_length=20, verbose_name='银行卡号')
    people = models.CharField(max_length=20, verbose_name='持有人')
    vest = models.CharField(max_length=100, verbose_name='银行卡归属')
    Type = models.CharField(max_length=100, verbose_name='类型')
    phone = models.CharField(max_length=11, verbose_name='手机号')
    balance = models.IntegerField(verbose_name='余额')

yujiaxm/forms.py
from django.forms import ModelForm,Form,CharField,PasswordInput,TextInput
from django.contrib.auth import models,authenticate
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

class Login(Form):
    name = CharField(label='账户名',widget=TextInput(attrs={'placeholder':"请输入您的账号或邮箱"}))
    password = CharField(widget=PasswordInput(attrs={'placeholder':"请输入密码"}),label='密码')
    class Meta:
        model = models.User
        fields = ['name','password']
        widgets = {
            'password': PasswordInput
        }
    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name',None)
        password = cleaned_data.get('password',None)
        if name and password:
            user=authenticate(username=name,password=password)
            if not user:
                raise ValidationError('用户名密码错误')
            else:
                self.user=user

class Register(Form):
    name = CharField(label='账户名',widget=TextInput(attrs={'placeholder':"请输入您的账号或邮箱"}),error_messages={'required':u'账号重复'})
    password = CharField(widget=PasswordInput(attrs={'placeholder':"请输入验证码"}),label='验证码')
    class Meta:
        model = models.User
        fields = ['name','password']
        widgets = {
            'password': PasswordInput
        }
        labels = {
            'name': '用户名',
            'password': '验证码',
        }
    def clean(self):
        print('------------------')
        cleaned_data = super().clean()
        username = cleaned_data.get("name",None)
        username_list=models.User.objects.all().values_list('username')
        if username:
            for i in username_list:
                if username in i:
                    raise ValidationError(
                        '用户名已存在，请重新输入'
                    )
        return cleaned_data

yujiaxm/views.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from .forms import Login,Register
from django.contrib.auth import login as login1,models
from django.contrib.auth import authenticate,login as login1
from .models import *
from math import radians, cos, sin, asin, sqrt
from django.views.decorators.csrf import csrf_exempt
import json,re
# from geopy.distance import geodesic
# Create your views here.

def login(request):
    if request.method == "GET":
        form = Login()
        return render(request,'zzy/login.html/',{'form':form})
    else:
        form = Login(request.POST)

        if form.is_valid():
            # 成功
            login1(request, form.user)
            jd = request.POST['jd']
            wd = request.POST['wd']
            wz = request.POST['wz']
            if jd and wd and wz:
                if request.user.info:
                    print(123)
                    request.user.info.create(distance='%s,%s' % (jd, wd), name=wz)
                else:
                    request.user.update(distance='%s,%s' % (jd, wd), name=wz)
            return redirect(reverse('yujiaxm:order'))
        else:
            # 验证失败
            return render(request,'zzy/login.html',{'form':form})

def register(request):
    if request.method == 'GET':
        form = Register()
        form.fields['name'].help_text = None
        return render(request, 'zzy/register.html', {'form': form})
    else:
        form = Register(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            from django.contrib.auth.hashers import make_password
            models.User.objects.create(username=data['name'], password=make_password(data['password']))
            return redirect(reverse('yujiaxm:login'))
        else:
            return render(request, 'zzy/register.html', {'form': form})


def index(request):  # 个人中心
    return render(request, "hq/index.html")

def history(request):  # 历史搜索
    return render(request,"hq/history.html")

def search(request): # 搜索界面
    obj=Search.objects.all().order_by('-times')
    if len(obj)>4:
        obj=obj[0:4]
    return render(request,"hq/search.html",{'obj':obj})

def exploration(request,con): #　结果
    if request.method == 'GET':
        obj=Search.objects.filter(con=con)
        if obj:
            Search.objects.filter(con=con).update(times=Search.objects.filter(con=con)[0].times+1)
        else:
            Search.objects.create(con=con)
    obj=Place.objects.all()
    res=[]
    yjd,ywd=request.user.info.distance.split(',')
    jl_list=[]
    for i in obj:
        if con in i.username:
            xjd,xwd=i.distance.split(',')
            jl=round(haversine(float(yjd), float(ywd), float(xjd), float(xwd)),2)
            jl_list.append(jl)
            print(i)
            res.append(i)
    if len(res)==0:
        return redirect(reverse('yujiaxm:discovery'))
    lbt=[]
    if len(res)>3:
        lbt=res[0:3]
    return render(request,"hq/exploration.html",{'res':res,'num':len(res),'str':str,'lbt':lbt,'jl_list':jl_list})

# 计算距离
def haversine(lon1, lat1, lon2, lat2):  # 经度1，纬度1，经度2，纬度2 （十进制度数）
    # 将十进制度数转化为弧度
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine公式
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * asin(sqrt(a))
    r = 6371  # 地球平均半径，单位为公里
    return c * r

def discovery(request): # 无
    return render(request,"hq/Discovery.html")



def yyxq(request,d_id):
    if d_id:
        dd = Dingdan.objects.filter(id=d_id)[0]
        return render(request,'xing/xing-yyxq.html',{'i':dd})

def ddxq(request,id):
    xk = Xuanke.objects.filter(id=id)[0]
    dd=[]
    if id:
        Dingdan.objects.create(author=request.user,name=xk.c_id,xuke_id=xk,price=xk.price,riqi=xk.riqi,shijianduan=xk.shijianduan,chance=xk.chance)
        dd=Dingdan.objects.all().order_by('-c_time').first()
    print(dd)
    return render(request,'xing/xing-ddxq.html',{'dd':dd})

@csrf_exempt
def xk(request,c_id):

    xk = Xuanke.objects.filter(c_id=c_id)
    return render(request,'xing/scheduled.html',{'xk':xk})


def fabu(request):
    return render(request,'xing/xing-fabu.html')

def duihua1(request):
    return render(request,'xing/xing-duihua1.html')

def duihua2(request):
    return render(request,'xing/xing-duihua2.html')

def changguanxq(request,id):
    vd=[]
    pl=[]
    try:
        vd = Venue_details.objects.filter(c_id=Place.objects.filter(id=id)[0])[0]
        pl = Pinglun.objects.filter(c_id=Place.objects.filter(id=id)[0])
    except:
        pass
    print(pl)
    return render(request,'xing/dj_index.html',{'vd':vd,'pl':pl,'id':id})

def dj_swan(request):
    dd = Dongzuo_details.objects.all
    return render(request,'xing/dj_swan.html',{'dd':dd})


def ddxqb(request):
    if request.user:
        dd = Dingdan.objects.filter(author=request.user)
        return render(request,'xing/xing-ddxqb.html',{'dd':dd})
    else:
        return redirect(reverse('yujiaxm:login'))


@csrf_exempt
def order(request):
    list_order = list(Place.objects.all().values())
    place = request.POST.get('place')

    print(place)
    # lnglat = str(request.POST.get('lnglat'))
    # print(lnglat)
    # s = tuple(re.findall("\d+.\d+", lnglat))
    # print(s)
    # distance = list(Place.objects.all().values('distance'))
    # print(distance)
    # for item in distance:
    #     item_dis = item['distance']
    #     print(item_dis)
        # data4 = geodesic((s), (item_dis))
        # print(data4)
    # data4=geodesic((37.82851,112.55176),(37.82861,112.55256))
    # print(data4)
    try:
        data = request.POST.get('data')
        data1 = json.loads(data)['city']
        data2 = json.loads(data)['district']
        data3 = []
        data3.append(data1)
        data3.append(data2)

        message={
            # 'm':list_order,
            's':data3,
            # 'm':data4,
        }
        return HttpResponse(json.dumps(message,ensure_ascii=False))
    except:
        return render(request, 'yoga/order.html', {'list_order': list_order,'place':place})

def act(request):
    act = Act.objects.all().values()
    return render(request,'yoga/act.html',{'act':act})
def category(request):
    cate = Category.objects.all().values()
    return render(request,'yoga/category.html',{'cate':cate})
def music(request):
    music = Music.objects.all().values()
    return render(request,'yoga/music.html',{'music':music})
def find(request):
    list_order = list(Place.objects.all().values())
    print(list_order)
    assess = list(Place.objects.all().values('assess'))
    print(assess)
    for i, v in enumerate(list_order):
        v['assess'] = assess[i]['assess']
    print(list_order)
    return render(request,'yoga/find.html',{'list_order':list_order})
def songs(request,id):
    songs = Music.objects.filter(id=id).values()
    gq = Song.objects.filter(t_id=id).values()
    print(gq)
    return render(request,'yoga/songs.html',{'songs':songs,'gq':gq})
def position(request):
    return render(request, 'yoga/position.html')


# 郑博

# 选择付款方式
@csrf_exempt
def period(request,id):
    dd = Dingdan.objects.filter(id=id).first()
    price = Dingdan.objects.filter(id=id).first()
    return render(request, 'zb/Payments.html', {'price':price, 'dd':dd})

# 银行卡付款
@csrf_exempt
def bank(request,id):
    user_id = request.user.id
    yh = BankCard.objects.filter(y_id=user_id).all()
    price = Dingdan.objects.filter(id=id).first()
    dd = Dingdan.objects.filter(id=id).first()
    if request.method == "POST":
        fl=request.POST.get('pas',None)
        if fl:
            password = request.user.info.password
            if password == fl:
                user = request.user.username
                ye = request.POST.get('yue', None)
                xf = request.POST.get('xf', None)
                kh = request.POST.get('kahao', None)
                kou = int(ye)-int(xf)
                BankCard.objects.filter(card=kh).update(balance=kou)
                return HttpResponse('ok')
            else:
                return HttpResponse('密码错误')
        else:
            return HttpResponse('网络连接中断')
    else:
        return render(request, 'zb/payment.html',{'yh':yh ,'price':price, 'dd':dd})

yujiaxm/templates/xing/dj_index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
        {% load static %}
    <script src="{% static 'dj/dj_js/rem(1).js' %}"></script>
    <link rel="stylesheet" href="{% static 'dj/dj_css/dj_index.css' %}">
    <script src="{% static 'xing/js/jQuery.js'%}"></script>
    <title>Document</title>
</head>
<body>
    <header></header>
    <div id="backar">
        <a href=""><img src="{% static 'dj/dj_img/xing-back.png'%}" alt="" id="back"></a>
        <div id="wenzi">禅瑜伽馆</div> 
    </div>
    <img src="{% static 'dj/dj_img/QQ浏览器截图20180905224444 拷贝.png'%}" alt="" style="width:6.94rem;height:3.5rem;margin-left: 0.28rem;margin-top: 0.71rem;">
    <div class="dingyue"><p>推荐</p></div>
    <div class="dingyue1"><p>订阅</p></div>
    <div class="we">
        <table>
            <tr>
                <td></td>
                <td>Mon8.10</td>
                <td>Mon8.11</td>
                <td>Mon8.12</td>
                <td>Mon8.13</td>
                <td>Mon8.13</td>
                <td>Mon8.13</td>
            </tr>
            <tr>
                <td>剩余</td>
                <td>3</td>
                <td>5</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>2</td>
            </tr>
            <tr>
                <td>免费</td>
                <td>3</td>
                <td>5</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>2</td>
            </tr>
            <tr>
                <td>优惠</td>
                <td>3</td>
                <td>5</td>
                <td>6</td>
                <td>6</td>
                <td>7</td>
                <td>2</td>
            </tr>
        </table>
    </div>
    <img src="{% static 'dj/dj_img/location.png'%}" alt="" style="width:0.44rem;height:0.5rem;margin-left: 0.24rem;margin-top: 0.26rem;">
    <div class="zi">{{ vd.c_id.place }}</div>
    <div class="tu1">
        <img src="{% static 'dj/dj_img/电话(2).png'%}" alt="" style="width:0.44rem;height:0.5rem;">
    </div>
    <div class="zi1">预约电话<span id="phnumber">{{ vd.phnumber }}</span></div>
    <div class="tu2">
            <img src="{% static 'dj/dj_img/椭圆 16.png'%}" alt="" style="width:0.44rem;height:0.44rem;">
        </div>
    <div class="zi2">场馆服务</div>
    <div id="forgot">

        <div class="omg">
            <ul>{% load poll_extras %}{{ value | fuwu:vd.server |safe}}</ul>
        </div>
    </div>
    <div class="tu3">
            <img src="{% static 'dj/dj_img/商店 拷贝.png'%}" alt="" style="width:0.44rem;height:0.44rem;">
        </div>
    <div class="zi3">场馆特色</div>
    <div class="bus">
        <ul>{{ value | tese:vd.tese |safe}}</ul>
    </div>
    <div class="user">
        <img src="{% static 'dj/dj_img/椭圆17拷贝3.png'%}" alt="" class="userdj">
        <div class="user1">用户评论&nbsp（165）</div>
        <img src="{% static 'dj/dj_img/more 拷贝.png'%}" alt="" class="user2">
    </div>
    <div class="rng">
        <h1>4.8</h1>
        <div class="zonghe">综合评价</div>
        <img src="{% static 'dj/dj_img/图层 4.png'%}" alt="" class="rng1" style="width: 1.5rem;height: 0.3rem;">
        <div class="shuxian"></div>
        <div class="haop">好评率%98</div>
    </div>
    {% for i in pl %}
    <div class="edg">
        <img src="{% static 'dj/dj_img/形状 1 副本 拷贝.png'%}" alt="" style="width:0.8rem;height:0.8rem;" class="edg1">
        <div class="shuzi">{{ i.author.username }}</div>
        <div class="riqi">{{ i.time }}</div>
    </div>
    <div class="chan">{{ i.con }}</div>
    {% endfor %}
    <div class="chan"></div>
    <a href="{% url 'yujiaxm:xk' c_id=id %}" id="btn">
        <button>立即预约</button>
    </a>
     
</body>
<script>
    changguan = $('#wenzi').text()
    $.ajax({
        url:'/xing/changguanxq/',
        type:'POST',
        data:{
            changguan:changguan
        },
        dataType: "dataType",
        success: function () {
                
        }
    })
</script>
</html> 

yujiaxm/templates/xing/dj_swan.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=0,minimal-ui">
	<title>天鹅颈训练</title>
	<script src="{% static 'dj/dj_js/rem(1).js'%}"></script>
	<link rel="stylesheet" href="https://at.alicdn.com/t/font_992846_iieqmdh5ghs.css">
	<link rel="stylesheet" href="{% static 'dj/dj_css/dj_swan.css'%}">
</head>
<body>
	<img src="{% static 'dj/dj_img/微信图片_20190103171734.png'%}" alt="">
	<video src="{% static 'xing/img/40948705-1-6.mp4' %}" id="yujiashipin" autoplay="autoplay" controls="controls"></video>
	{% for i in dd %}
	<h2>{{ i.name }}</h2>
	<div class="time">
		<ul>
			<li>课时</li>
			<li>时长</li>
			<li>难度</li>
		</ul>
	</div>
	<div class="num">
		<ul>
			<li>{{ i.ke_time }}</li>
			<li>{{ i.shi_time }}</li>
			<li>{{ i.rank }}</li>
		</ul>
	</div>
	<div class="course">
		<span>课程<span class="present">介绍</span></span>
		<h3>{{ i.produce }}</h3>
	</div>
	<div class="more">查看更多</div>
	<div class="course">
		<span>适合<span class="present">人群</span></span>
		<h3>{{ i.people }}</h3>
	</div>
	{% endfor %}
	<footer>
		<div class="left">
			<i class="iconfont icon-bofang"></i>
			<span>播放</span>
		</div>
		<div class="right">
			<span>缓存</span>
			<i class="iconfont icon-xiazai"></i>
		</div>
	</footer>
</body>
</html>

yujiaxm/templates/xing/xing-ddxq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'xing/css/xing-yyddxq.css'%}">
    <script src="{% static 'xing/js/jQuery.js'%}"></script>
    <script src="{%static 'xing/js/rem(1).js'%}"></script>
    <title>订单详情</title>
</head>
<body>
    <header></header>
    <div id="backar">
        <a href=""><img src="{%static 'xing/img/xing-back.png'%}" alt="" id="back"></a>
    </div>
    <div id="ddxq">订单详情</div>
    <a href="yyxq">
        <div id="w_xq">
            <div id="xqq">{{ dd.name.username }}</div>
            <div id="xxxx">
                <img src="{%static 'xing/img/xqtu.png'%}" alt="" id="xqtu">
                <div id="you_xqing">
                    <div id="you_xqing1">有限时间：<span id="shijian">{{ dd.riqi }}</span></div>
                    <div id="you_xqing1" style="letter-spacing: 0.22rem;">下午：<span id="shijian">{{ dd.shijianduan }}</span><div id="didian">{{ i.didian }}</div></div>
                    <div id="you_xqing1">已选：<span id="">{{ dd.chance }}</span>场次</div>
                </div>
            </div>
            <div id="zongjia">总计：<span id="zongnum">{{ dd.price }}</span>元</div>
        </div>
    </a>
    <!--进入付款-->
    <a href="{% url 'yujiaxm:period' id=dd.id %}">
        <button id="queren">确认订单</button>
    </a> 
</body>
</html>

yujiaxm/templates/xing/xing-ddxqb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'xing/css/xing-yyddxq.css'%}">
    <script src="{% static 'xing/js/jQuery.js'%}"></script>
    <script src="{%static 'xing/js/rem(1).js'%}"></script>
    <title>订单详情</title>
</head>
<body>
    <header></header>
    <div id="backar">
        <a href=""><img src="{%static 'xing/img/xing-back.png'%}" alt="" id="back"></a>
    </div>
    <div id="ddxq">订单详情</div>
    {% for i in dd %}
    <a href="yyxq">
        <div id="w_xq">
            <div id="xqq">{{ i.neirong }}</div>
            <div id="xxxx">
                <img src="{%static 'xing/img/xqtu.png'%}" alt="" id="xqtu">
                <div id="you_xqing">
                    <div id="you_xqing1">有限时间：<span id="shijian">{{ i.riqi }}</span></div>
                    <div id="you_xqing1" style="letter-spacing: 0.22rem;">下午：<span id="shijian">{{ i.shijianduan }}</span><div id="didian">{{ i.didian }}</div></div>
                    <div id="you_xqing1">已选：<span id="">{{ i.chance }}</span>场次</div>
                </div>
            </div>
            <div id="zongjia">总计：<span id="zongnum">{{ i.price }}</span>元</div>
        </div>
    </a>
    {% endfor %}
</body>
</html>